# Generated by Django 2.1.2 on 2018-10-20 14:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, upload_to='profile_pics')),
                ('bio', models.TextField(blank=True, max_length=1000)),
                ('twitter', models.CharField(blank=True, max_length=16)),
                ('facebook', models.CharField(blank=True, max_length=66)),
                ('user', models.OneToOneField(on_delete='CASCADED', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
