# Generated by Django 2.1.2 on 2018-10-21 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='speaker',
            old_name='user',
            new_name='speaker',
        ),
    ]
