# Generated by Django 2.1.2 on 2018-10-21 05:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181021_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='speaker',
            field=models.OneToOneField(on_delete='CASCADED', related_name='speaker', to=settings.AUTH_USER_MODEL),
        ),
    ]
