# Generated by Django 2.1.2 on 2018-10-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181021_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('abstract', models.TextField(max_length=2000)),
                ('speaker', models.ForeignKey(on_delete='DO_NOTHING', related_name='session_speaker', to='app.Speaker')),
            ],
        ),
    ]
