# Generated by Django 2.1.2 on 2018-11-03 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181027_0730'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vcount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('V_name', models.CharField(blank=True, max_length=25)),
                ('V_email', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='going',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='speaker',
            name='picture',
            field=models.ImageField(blank=True, default='pic_folder/None.jpg', null=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='session',
            field=models.ForeignKey(on_delete='DO_NOTHING', related_name='session', to='app.session'),
        ),
        migrations.AddField(
            model_name='vcount',
            name='session',
            field=models.ForeignKey(on_delete='DO_NOTHING', related_name='session_title', to='app.session'),
        ),
        migrations.AddField(
            model_name='vcount',
            name='visitor',
            field=models.ForeignKey(on_delete='DO_NOTHING', related_name='visitor_name', to='app.Visitor'),
        ),
    ]
