# Generated by Django 2.1.2 on 2018-11-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20181103_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='picture',
            field=models.ImageField(blank=True, default='None.jpg', upload_to='profile_pics'),
        ),
    ]
