# Generated by Django 2.1.2 on 2018-11-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181105_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='session',
        ),
        migrations.AlterField(
            model_name='speaker',
            name='picture',
            field=models.ImageField(default='None.png', upload_to='profile_pics'),
        ),
    ]
