# Generated by Django 2.1.2 on 2018-11-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20181112_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='V_message',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
